# Generated by Django 5.0.4 on 2024-04-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField(max_length=1000)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateField(verbose_name='date published the event will be published in the FE')),
                ('launch_date', models.DateField(verbose_name='data the event is officil launched')),
                ('register_start_date', models.DateField(verbose_name='date event registration starts')),
                ('register_end_date', models.DateField(verbose_name='date event registration ends')),
                ('image', models.ImageField(blank=True, null=True, upload_to='.event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
